# Generated by Django 5.2.17 on 2026-10-10 17:26
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_post_tags'),
    ]

    operations = [
        TrigramExtension(),
    ]
